import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { baseUrl } from "../config"; // baseUrl is assumed to be correctly defined here

// Define the API slice using RTK Query
export const childApi = createApi({
  reducerPath: "childApi",
  baseQuery: fetchBaseQuery({ baseUrl }), // You can also pass headers or other options here
  endpoints: (builder) => ({
    childUser: builder.mutation({
      query: (userData) => ({
        url: "/child",
        method: "POST",
        body: userData,
      }),
    }),
  }),
});

// Export the hooks generated by the API slice
export const { useChildUserMutation } = childApi;
